development:
  adapter: postgresql
  encoding: unicode
  database: lighters_development
  pool: 5
  username: eveyz
  password: saiop147

test:
  adapter: postgresql
  encoding: unicode
  database: lighters_test
  pool: 5
  username: eveyz
  password: saiop147

production:
  adapter: postgresql
  encoding: unicode
  database: lighters_production
  pool: 5
  username: eveyz
  password: saiop147
